elasticsearch_engineer_task:
  description: >
    Create a eslog example.
  expected_output: >
    A file log
    
nodejs_developer_task:
  description: >
    Create a code in NodeJS to transform a EslasticSearch log in cloudwatch log.  
  expected_output: >
    A file name app.js with code NodeJS 

dotnet_developer_task:
  description: >
    Create a code in .NET to transform a EslasticSearch log in cloudwatch log.  
  expected_output: >
    A file name app.cs with code C# 

